# Generated by Django 4.2.1 on 2023-05-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_user_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
